SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

USE `home_inventory`;


ALTER TABLE items ADD inventory_id int(11) NOT NULL DEFAULT 1;
ALTER TABLE items ADD CONSTRAINT fk_inventory_id FOREIGN KEY (inventory_id) 
REFERENCES inventories(id) ON DELETE CASCADE ON UPDATE CASCADE;


  
COMMIT;